### ISSUE TITLE
Table View: to visualize the tables and columns

### ISSUE THREAD

**Issue by fasteddys** [zamgi/MsSqlServerDatabaseTablesGraph#1]
Hello this is very nice, can you please add this, the below code will give you a list of tables automatically.. to feed into the view

# All DB Tables

```
var allTableNamesinDatabase = context.Model.GetEntityTypes()
    .Select(t => t.GetTableName())
    .Distinct()
    .ToList();
```

**Comment by zamgi** [comment]
hi,

as you can see, my friend, this application doesn't use the entity framework and the like, because it ... is not needed (no one)))
